image: mcr.microsoft.com/vscode/devcontainers/java:17

tasks:
  - name: Run Selenium Tests
    init: mvn clean compile
    command: mvn clean test

vscode:
  extensions:
    - vscjava.vscode-java-pack
